### ISSUE TITLE
[AlternateRacialTraits] [Warning] Blueprint guid dfcc0aa98c3d4826a7e60911cf588b45 does not match provided guid 

### ISSUE THREAD

**Issue by tafeilgh** [microsoftenator2022/AlternateRacialTraits#10]
[AlternateRacialTraits] [Warning] Missing initializer for AlternateRacialTraits.Features.RacialWeaponFamiliarities+WeaponFamiliarityComponent. Using fallback
[AlternateRacialTraits] [Warning] Blueprint guid dfcc0aa98c3d4826a7e60911cf588b45 does not match provided guid 242a1d4af3604b2c8da71fb02305e3f7. Replacing blueprint guid.
Found this line in the player.log

**Comment by aaronmaslen** [comment]
Well spotted. Thanks.
Should be fixed in v1.5.5
