### ISSUE TITLE
Request - Hook into ModFinder

### ISSUE THREAD

**Issue by JamesEhren** [microsoftenator2022/AlternateRacialTraits#2]
Hook ART into ModFinder for easy user tracking and updates: https://github.com/Pathfinder-WOTR-Modding-Community/ModFinder

**Comment by biship** [comment]
PLease and thank you!

**Comment by aaronmaslen** [comment]
It should be there. It was added [here](https://github.com/Pathfinder-WOTR-Modding-Community/ModFinder/pull/81)

**Comment by biship** [comment]
It doesn't work. Modfinder is not able to determine the current version AlternateRacialTraits.
I think it is because you put a **v** infront of your releases on github. I checked a few other working mods and on github they just use numbers for their releases. @microsoftenator2022
