### ISSUE TITLE
[BUG] Humans can't learn the Skilled racial ability.

### ISSUE THREAD

**Issue by Endarire** [microsoftenator2022/AlternateRacialTraits#3]
Greetings, @microsoftenator2022!

Humans can't learn the Skilled racial ability with this mod.

Thankee for fixing!

**Comment by aaronmaslen** [comment]
Humans start with Skilled. If you want to keep it, select "None" after picking any other traits (that don't replace Skilled)

**Comment by PawelS-AoW** [comment]
They don't seem to lose the skill point (at least at character creation, I haven't checked at gaining a level) when they pick something that replaces Skilled though.

**Comment by microsoftenator2022** [comment]
The Skilled feature *is* present (or you wouldn't be able to take any feature that replaces it) but it does not seem to be recalculating skill points when it is added/removed. 🤔
