### ISSUE TITLE
New Skilled Aasimar and Tiefling traits not working

### ISSUE THREAD

**Issue by Gyrados15** [microsoftenator2022/AlternateRacialTraits#7]
So these new traits don't seem to be working, they do show up on the Creation screen and in Toybox but don't add the extra point.

As a Workaround I'm just setting the Human skilled Feature in Toybox afterwards as that then calculates correctly.

**Comment by aaronmaslen** [comment]
"Skilled" feat refers to the heritage skill bonuses. It is not like the Human Skilled feat.
![image](https://github.com/microsoftenator2022/AlternateRacialTraits/assets/5466817/acb9ed5e-379f-4b7a-868e-b270998b4596)

**Comment by Gyrados15** [comment]
Ahh I see thanks
