### ISSUE TITLE
Crusading Magic did not disable race magic

### ISSUE THREAD

**Issue by ForbAvalon** [microsoftenator2022/AlternateRacialTraits#9]
Even I choosed Crusading Magic, I still got Restoration Lesser

**Comment by aaronmaslen** [comment]
It works for me. Are you perhaps using other mods that modify Aasimar?

![image](https://github.com/microsoftenator2022/AlternateRacialTraits/assets/5466817/b3b00f9f-48b9-43f1-9065-389c0b66bac4)
